"""add team model

Revision ID: 903ca176ecd2
Revises: eb67bcabd147
Create Date: 2025-04-13 19:42:20.574524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903ca176ecd2'
down_revision: Union[str, None] = 'eb67bcabd147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('steam_link', sa.String(), nullable=False))
    op.add_column('user', sa.Column('is_captain', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('game', sa.String(), nullable=False))
    op.add_column('user', sa.Column('team_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'team_id')
    op.drop_column('user', 'game')
    op.drop_column('user', 'is_captain')
    op.drop_column('user', 'steam_link')
    op.drop_table('team')
    # ### end Alembic commands ###
