"""tg link now only for captains

Revision ID: 9a98c9831b59
Revises: 31308e839e24
Create Date: 2025-04-27 22:47:34.473800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a98c9831b59'
down_revision: Union[str, None] = '31308e839e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tg_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'tg_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
